# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Anthony Ezeh
description: >- # this means to ignore newlines until "baseurl:"
  Highly experienced Full Stack Developer with over 14 years of experience in front-end, back-end, desktop and mobile app development.   Skilled in incorporating input into projects, with the ability to build from scratch or improve already existing code. 
  Good eye for design, functionality and user experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://anthonioez.github.io/
github_username:  anthonioez
cover: /static/img/og.png
logo: /static/img/emojis/sunglasses.png
freelancer: https://freelancer.com/u/anthonioez
upwork: https://www.upwork.com/freelancers/anthonioez
social:
  - title: upwork
    url: https://www.upwork.com/freelancers/anthonioez
  - title: freelancer
    url: https://freelancer.com/u/anthonioez
  - title: github
    url: https://github.com/anthonioez
  - title: behance
    url: https://behance.net/anthonioez

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'src'
  - 'gulpfile.js'
  - 'gruntfile.js'
  - 'package.json'
  - 'package-lock.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
